name: securevault
description: SecureVault - Zero-Knowledge Password Manager
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.1

  # Networking
  http: ^1.2.0
  dio: ^5.4.0

  # Security / Crypto
  pointycastle: ^3.7.3
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.0.0

  # Biometrics
  local_auth: ^2.1.8

  # Clipboard
  clipboard: ^0.1.3

  # URL Launcher
  url_launcher: ^6.2.2

  # Local Database Cache
  sqflite: ^2.3.2
  path: ^1.8.3

  # File handling and sharing
  path_provider: ^2.1.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
